OUTNAME=test

MYSQLCFG=mysql_config

INCDIRS+= ..
LIBDIRS+= ..

SRCS+= test.cpp
FLAGS+= `$(MYSQLCFG) --cflags`

FLAGS+= -ggdb

LIBS+=  -lds
LIBS+= -L/usr/lib/mysql -lmysqlclient -lcrypt -lnsl -lm -lc -lnss_files -lnss_dns -lresolv
LIBS+= -lz 
all:
	$(CXX) $(FLAGS) -I$(INCDIRS) -L$(LIBDIRS) $(LIBS) $(SRCS) -o$(OUTNAME).elf

clean:
	rm *.elf